# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_SENSORS_SSC)	+= sensors_ssc.o
obj-$(CONFIG_SENSORS)		+= sensors_core.o
obj-$(CONFIG_SENSORS_SX9360)	+= sx9360.o
obj-$(CONFIG_SENSORS_A96T3X6)	+= a96t3x6.o