#
# Makefile for the netfilter modules on top of IPv4.
#
obj-y += oppo_app_monitor.o
oppo_app_monitor-objs := oppo_apps_monitor.o oppo_apps_power_monitor.o

#obj-y : oppo_app_monitor.o
#oppo_app_monitor-y : oppo_apps_power_monitor.o oppo_apps_monitor.o