#
# mAFPC Object
# namd : ss_dsi_mafpc_"DDI NAME".c
#

ccflags-y := -I$(srctree)/include/drm -I$(srctree)/techpack/display/msm -I$(srctree)/techpack/display/msm/dsi -I$(srctree)/techpack/display/msm/sde -I$(srctree)/techpack/display/msm/samsung

obj-y += ss_dsi_mafpc_HAB.o
